# Generated by Django 6.0.2 on 2026-02-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table='administradores',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes',
        ),
    ]
