# Generated by Django 6.0.2 on 2026-03-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.paciente')),
            ],
            options={
                'db_table': 'pacientes_users',
            },
        ),
    ]
