# Generated by Django 6.0.2 on 2026-02-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_administrador_table_alter_paciente_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AddField(
            model_name='administrador',
            name='administrador_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='paciente_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
