# Generated by Django 6.0.2 on 2026-03-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDaltonismo',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias_daltonismo',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPrueba',
            fields=[
                ('respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respuestas_prueba',
            },
        ),
        migrations.CreateModel(
            name='SesionPrueba',
            fields=[
                ('sesion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'sesiones_prueba',
            },
        ),
        migrations.CreateModel(
            name='PreguntaPrueba',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('tipo_pregunta', models.CharField(blank=True, max_length=50, null=True)),
                ('recurso_visual', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('obligatoria', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo')),
            ],
            options={
                'db_table': 'preguntas_prueba',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('opcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(max_length=100)),
                ('valor_opcion', models.CharField(blank=True, max_length=50, null=True)),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntaje', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.preguntaprueba')),
            ],
            options={
                'db_table': 'opciones_respuesta',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('prueba_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prueba', models.CharField(max_length=100)),
                ('tipo_prueba', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo')),
            ],
            options={
                'db_table': 'pruebas',
            },
        ),
    ]
