# Generated by Django 6.0.2 on 2026-03-04 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pruebas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preguntaprueba',
            name='prueba',
            field=models.ForeignKey(db_column='prueba_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba'),
        ),
        migrations.AddField(
            model_name='respuestaprueba',
            name='opcion',
            field=models.ForeignKey(blank=True, db_column='opcion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebas.opcionrespuesta'),
        ),
        migrations.AddField(
            model_name='respuestaprueba',
            name='pregunta',
            field=models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.preguntaprueba'),
        ),
        migrations.AddField(
            model_name='sesionprueba',
            name='paciente',
            field=models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='sesionprueba',
            name='prueba',
            field=models.ForeignKey(db_column='prueba_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba'),
        ),
        migrations.AddField(
            model_name='respuestaprueba',
            name='sesion',
            field=models.ForeignKey(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba'),
        ),
    ]
