# Generated by Django 6.0.2 on 2026-02-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_metricarendimiento_paciente_and_more'),
        ('pruebas', '0001_initial'),
        ('usuarios', '0002_alter_administrador_table_alter_paciente_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionprueba',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='sesionprueba',
            name='prueba',
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.preguntaprueba'),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto_opcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaprueba',
            name='categoria',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo'),
        ),
        migrations.AlterField(
            model_name='preguntaprueba',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaprueba',
            name='prueba',
            field=models.ForeignKey(db_column='prueba_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='categoria',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrador'),
        ),
        migrations.AlterModelTable(
            name='categoriadaltonismo',
            table='categorias_daltonismo',
        ),
        migrations.AlterModelTable(
            name='opcionrespuesta',
            table='opciones_respuesta',
        ),
        migrations.AlterModelTable(
            name='preguntaprueba',
            table='preguntas_prueba',
        ),
        migrations.AlterModelTable(
            name='prueba',
            table='pruebas',
        ),
        migrations.DeleteModel(
            name='RespuestaPrueba',
        ),
        migrations.DeleteModel(
            name='SesionPrueba',
        ),
    ]
