# Generated by Django 6.0.2 on 2026-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='creado_por',
        ),
    ]
