# Generated by Django 6.0.2 on 2026-02-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_remove_sesionprueba_paciente_and_more'),
        ('usuarios', '0003_remove_administrador_id_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadaltonismo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='opcionrespuesta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='preguntaprueba',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='id',
        ),
        migrations.AddField(
            model_name='categoriadaltonismo',
            name='categoria_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='opcion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='preguntaprueba',
            name='pregunta_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='prueba',
            name='prueba_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto_opcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntaprueba',
            name='orden',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrador'),
        ),
    ]
