# Generated by Django 6.0.2 on 2026-02-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_remove_categoriadaltonismo_id_and_more'),
        ('usuarios', '0003_remove_administrador_id_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionPrueba',
            fields=[
                ('sesion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
                ('prueba', models.ForeignKey(db_column='prueba_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba')),
            ],
            options={
                'db_table': 'sesiones_prueba',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPrueba',
            fields=[
                ('respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
                ('opcion', models.ForeignKey(blank=True, db_column='opcion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebas.opcionrespuesta')),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.preguntaprueba')),
                ('sesion', models.ForeignKey(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba')),
            ],
            options={
                'db_table': 'respuestas_prueba',
            },
        ),
    ]
