# Generated by Django 6.0.2 on 2026-02-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pruebas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metrica', models.CharField(max_length=100)),
                ('valor_metrica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.paciente')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebas.sesionprueba')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeteccionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_detectado', models.CharField(max_length=50)),
                ('color_esperado', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField(default=0)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones_color', to='pruebas.sesionprueba')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.IntegerField()),
                ('nivel_confianza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('categoria_detectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo')),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba')),
            ],
        ),
    ]
