# Generated by Django 6.0.2 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaRendimiento',
            fields=[
                ('metrica_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metrica', models.CharField(max_length=100)),
                ('valor_metrica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metricas_rendimiento',
            },
        ),
        migrations.CreateModel(
            name='RegistroDeteccionColor',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_detectado', models.CharField(max_length=50)),
                ('color_esperado', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField(default=0)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registros_deteccion_color',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDiagnostico',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.IntegerField(blank=True, null=True)),
                ('nivel_confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resultados_diagnostico',
            },
        ),
    ]
