# Generated by Django 6.0.2 on 2026-02-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('pruebas', '0001_initial'),
        ('usuarios', '0002_alter_administrador_table_alter_paciente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricarendimiento',
            name='paciente',
            field=models.ForeignKey(blank=True, db_column='paciente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='registrodeteccioncolor',
            name='color_detectado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeteccioncolor',
            name='color_esperado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultadodiagnostico',
            name='categoria_detectada',
            field=models.ForeignKey(db_column='categoria_detectada', on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo'),
        ),
        migrations.AlterField(
            model_name='resultadodiagnostico',
            name='nivel_confianza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultadodiagnostico',
            name='puntaje_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='metricarendimiento',
            table='metricas_rendimiento',
        ),
        migrations.AlterModelTable(
            name='registrodeteccioncolor',
            table='registros_deteccion_color',
        ),
        migrations.AlterModelTable(
            name='resultadodiagnostico',
            table='resultados_diagnostico',
        ),
        migrations.CreateModel(
            name='SesionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
                ('prueba', models.ForeignKey(db_column='prueba_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba')),
            ],
            options={
                'db_table': 'sesiones_prueba',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
                ('opcion', models.ForeignKey(blank=True, db_column='opcion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebas.opcionrespuesta')),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.preguntaprueba')),
                ('sesion', models.ForeignKey(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='diagnostico.sesionprueba')),
            ],
            options={
                'db_table': 'respuestas_prueba',
            },
        ),
        migrations.AlterField(
            model_name='metricarendimiento',
            name='sesion',
            field=models.ForeignKey(blank=True, db_column='sesion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostico.sesionprueba'),
        ),
        migrations.AlterField(
            model_name='registrodeteccioncolor',
            name='sesion',
            field=models.ForeignKey(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='diagnostico.sesionprueba'),
        ),
        migrations.AlterField(
            model_name='resultadodiagnostico',
            name='sesion',
            field=models.OneToOneField(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='diagnostico.sesionprueba'),
        ),
    ]
