# Generated by Django 6.0.2 on 2026-03-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('pruebas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricarendimiento',
            name='paciente',
            field=models.ForeignKey(blank=True, db_column='paciente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='metricarendimiento',
            name='sesion',
            field=models.ForeignKey(blank=True, db_column='sesion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebas.sesionprueba'),
        ),
        migrations.AddField(
            model_name='registrodeteccioncolor',
            name='sesion',
            field=models.ForeignKey(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba'),
        ),
        migrations.AddField(
            model_name='resultadodiagnostico',
            name='categoria_detectada',
            field=models.ForeignKey(db_column='categoria_detectada', on_delete=django.db.models.deletion.CASCADE, to='pruebas.categoriadaltonismo'),
        ),
        migrations.AddField(
            model_name='resultadodiagnostico',
            name='sesion',
            field=models.OneToOneField(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba'),
        ),
    ]
