# Generated by Django 6.0.2 on 2026-02-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_metricarendimiento_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricarendimiento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registrodeteccioncolor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='respuestaprueba',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resultadodiagnostico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sesionprueba',
            name='id',
        ),
        migrations.AddField(
            model_name='metricarendimiento',
            name='metrica_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='registrodeteccioncolor',
            name='registro_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='respuestaprueba',
            name='respuesta_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='resultadodiagnostico',
            name='resultado_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sesionprueba',
            name='sesion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrodeteccioncolor',
            name='color_detectado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrodeteccioncolor',
            name='color_esperado',
            field=models.CharField(max_length=50),
        ),
    ]
