# Generated by Django 6.0.2 on 2026-02-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_remove_metricarendimiento_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaprueba',
            name='opcion',
        ),
        migrations.RemoveField(
            model_name='respuestaprueba',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestaprueba',
            name='sesion',
        ),
        migrations.RemoveField(
            model_name='sesionprueba',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='sesionprueba',
            name='prueba',
        ),
    ]
