# Generated by Django 6.0.2 on 2026-02-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0004_remove_respuestaprueba_opcion_and_more'),
        ('pruebas', '0004_sesionprueba_respuestaprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadodiagnostico',
            name='sesion',
            field=models.OneToOneField(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba'),
        ),
        migrations.AlterField(
            model_name='metricarendimiento',
            name='sesion',
            field=models.ForeignKey(blank=True, db_column='sesion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebas.sesionprueba'),
        ),
        migrations.AlterField(
            model_name='registrodeteccioncolor',
            name='sesion',
            field=models.ForeignKey(db_column='sesion_id', on_delete=django.db.models.deletion.CASCADE, to='pruebas.sesionprueba'),
        ),
        migrations.DeleteModel(
            name='RespuestaPrueba',
        ),
        migrations.DeleteModel(
            name='SesionPrueba',
        ),
    ]
